version: '3'
services:
  redis-cluster1:
    image: redis-cluster
    build: .
    ports:
      - '30001:30001'
    volumes:
      - './config/:/etc/redis-cluster/'
      - './scripts/start-server.sh:/scripts/start-server.sh'
    environment:
      - 'NODE_NUMBER=node1'
    command:
      - '/scripts/start-server.sh'
    container_name: redis-cluster1
    restart: always
  redis-cluster2:
    image: redis-cluster
    build: .
    ports:
      - '30002:30002'
    volumes:
      - './config/:/etc/redis-cluster/'
      - './scripts/start-server.sh:/scripts/start-server.sh'
    environment:
      - 'NODE_NUMBER=node2'
    command:
      - '/scripts/start-server.sh'
    container_name: redis-cluster2
    restart: always
  redis-cluster3:
    image: redis-cluster
    build: .
    ports:
      - '30003:30003'
    volumes:
      - './config/:/etc/redis-cluster/'
      - './scripts/start-server.sh:/scripts/start-server.sh'
    environment:
      - 'NODE_NUMBER=node3'
    command:
      - '/scripts/start-server.sh'
    container_name: redis-cluster3
    restart: always